name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=-4rcsb5##in5ny_du8)@fa5fd9)^k!qg@zx!pwno6y5-i$ps+m
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=NOtkqb4QpsQRfHRG049UY6fi
      - PASSAGE_API_KEY=bMMiDJRZn0.BB9kPEhhANKN5CsIksyNSn57j4TUlg3wYmjgvfn1LdDpQK7ywF1lWknE7JW0wBnL
    ports:
      - 8000:8000